apiVersion: v1
kind: Service
metadata:
  labels:
    service: instabook-api
  name: instabook-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: instabook-api
