apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: instabook-frontend
  name: instabook-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: instabook-frontend
  template:
    metadata:
      labels:
        service: instabook-frontend
        api: external
    spec:
      containers:
        - image: abhimanyudwivedi/instabook-frontend
          name: instabook-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"
      restartPolicy: Always
