apiVersion: v1
kind: Service
metadata:
  labels:
    service: instabook-frontend
  name: instabook-frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80
  selector:
    service: instabook-frontend
